version: "3.8"

services:
  db:
    image: mysql:5.7
    container_name: "hackernews-database"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: "hackernews"
      # You can use whatever password you like
      MYSQL_PASSWORD: "root"
      # Password for root access
      MYSQL_ROOT_PASSWORD: "dbpass"
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - "3306:3306"
    expose:
      # Opens port 3306 on the container
      - "3306"
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
  api:
    build: .
    container_name: "hackernews-graphql-api"
    environment:
      DB_USERNAME: "root"
      DB_PASSWORD: "dbpass"
      DB_HOST: "db"
      DB_PORT: "3306"
      DB_DB: "hackernews"
      PORT: "3030"
    ports:
      - "3030:3030"
    depends_on:
      - db
  pma:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    ports:
      - 5003:80
    environment:
      - "PMA_HOST=db"
      - "PMA_PORT=3306"
    container_name: golang-docker-pma
volumes:
  my-db:
